version: '3.8'
services:
  postgres:
    image: postgres:11.1 # use latest official postgres version
    env_file:
      - database.env # configure postgres
        # database.env
        # POSTGRES_USER=postgres
        # POSTGRES_PASSWORD=postgres
        # POSTGRES_DB=postgres
    volumes:
      - ./database/postgres:/var/lib/posgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis
    volumes:
      - ./database/redis/data:/var/lib/redis
      - ./database/redis/conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
